// Mocks generated by Mockito 5.4.5 from annotations
// in flutter_temeplete/test/features/todos/domain/get_todos_usecase.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter_temeplete/features/todos/domain/entities/todo_entity.dart'
    as _i3;
import 'package:flutter_temeplete/features/todos/domain/repositories/todo_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TodoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoRepository extends _i1.Mock implements _i2.TodoRepository {
  MockTodoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Todo> getTodos() =>
      (super.noSuchMethod(
            Invocation.method(#getTodos, []),
            returnValue: <_i3.Todo>[],
          )
          as List<_i3.Todo>);

  @override
  void addTodo(_i3.Todo? todo) => super.noSuchMethod(
    Invocation.method(#addTodo, [todo]),
    returnValueForMissingStub: null,
  );

  @override
  void toggleTodo(String? id) => super.noSuchMethod(
    Invocation.method(#toggleTodo, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void deleteTodo(String? id) => super.noSuchMethod(
    Invocation.method(#deleteTodo, [id]),
    returnValueForMissingStub: null,
  );
}
