name: flutter_temeplete
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  intl: any
  http: ^1.3.0
  skeletonizer: ^1.4.3
  logger: ^2.4.0
  equatable: ^2.0.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.3
  dartz: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  golden_toolkit: ^0.15.0
  test: ^1.25.15

flutter:
  uses-material-design: true
